# Generated by Django 5.2.4 on 2025-08-01 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicecommand',
            name='duration',
        ),
    ]
